language: php
sudo: true
services:
    - docker

env:
    - SYMFONY_VERSION="4.3.*" DB=mysql

before_install:
    - docker-compose up -d

install:
    - docker-compose exec app bash
    - composer install
