language: php
sudo: true
services:
    - docker

env:
    - SYMFONY_VERSION="3.0.*" DB=mysql

before_install:
    - docker-compose up -d
    - docker-compose exec app bash
    - composer self-update

install:
    - composer install
