version: "3.3"
services:
    traefik:
        image: traefik
        command: --docker --docker.exposedbydefault=true
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    app:
        image: thecodingmachine/php:7.2-v1-apache-node10
        labels:
          - traefik.enable=true
          - traefik.backend=app
          - traefik.frontend.rule=Host:app.localhost
        environment:
          APACHE_DOCUMENT_ROOT: public/
          PHP_EXTENSION_XDEBUG: 1
          # Symfony
          APP_ENV: dev
          APP_SECRET: 8d2a5c935d8ef1c0e2b751147382bc75
          DATABASE_URL: mysql://foo:bar@mysql:3306/foo # mysql://db_user:db_password@127.0.0.1:3306/db_name
        volumes:
          - ./app:/var/www/html:rw

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: foo
            MYSQL_USER: foo
            MYSQL_PASSWORD: bar
        volumes:
            - mysql_data:/var/lib/mysql
            - ./services/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        labels:
            - traefik.enable=true
            - traefik.backend=phpmyadmin
            - traefik.fromtend.rule=Host:phpadmin.app.localhost
        environment:
            PMA_HOST: mysql
            PMA_USER: foo
            PMA_PASSWORD: bar
volumes:
    mysql_data:
        driver: local
