language: php
sudo: true
services:
    - mysql
cache:
    directories:
        - $HOME/.composer/cache/files
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true
    include:
        - php: 7.0
        - php: hhvm
    allow_failures:
        - php: hhvm
env:
    - SYMFONY_VERSION="4.3.*" DB=mysql

before-install:
    - composer self-update

install:
    # - composer install
    # - cp .env.dist .env
    # - php bin/console doctrine:database:create --env=test
    # - php bin/console doctrine:schema:create --env=test
    # - php bin/console doctrine:fixtures:load -n --env=test

script:
    - php bin/phpunit

notifications:
    email: samuil.ivanovbg@gmail.com
